name: raid_app
description: Raid artifact scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_paddle_ocr_v5: ^0.0.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  image: ^4.1.0
  snapframes: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/det.onnx
    - assets/models/rec.onnx
    - assets/models/dict.txt
